services:
  - type: web
    name: request_flaskapi
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 8080
    autoDeploy: true
